#!/usr/bin/env bash
set -o errexit
set -o pipefail
set -o nounset
# set -o xtrace
__dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
__root="$(cd "$(dirname "${__dir}")" && pwd)"
__file="${__dir}/$(basename "${BASH_SOURCE[0]}")"
__base="$(basename ${__file} .sh)"
arg1="${1:-}"

########################################################################
# Gets meta language dependencies.

mvn dependency:copy-dependencies
mkdir -p src/main/resources/meta-languages/
cp -t src/main/resources/meta-languages/ target/dependency/*.spoofax-language
