#!/usr/bin/env bash
set -o errexit
set -o pipefail
set -o nounset
# set -o xtrace
__dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
__root="$(cd "$(dirname "${__dir}")" && pwd)"
__file="${__dir}/$(basename "${BASH_SOURCE[0]}")"
__base="$(basename ${__file} .sh)"
arg1="${1:-}"

########################################################################
# Installs IntelliJ IDEA Community Edition
# and creates a shortcut.

IDEA_VERSION="14.1.4"
IDEA_URL="https://download.jetbrains.com/idea/ideaIC-${IDEA_VERSION}.tar.gz"
IDEA_SRC_URL="http://download.jetbrains.com/idea/ideaIC-${IDEA_VERSION}-src.tar.bz2"

#----------------------------------------------------------------------#
echo "Downloading IntelliJ IDEA..."

if [ ! -f idea.tar.gz ]; then
    wget -O idea.tar.gz ${IDEA_URL}
fi

#----------------------------------------------------------------------#
echo "Installing IntelliJ IDEA in local repo..."

mvn install:install-file \
	"-Dfile=idea.tar.gz" \
	"-DgroupId=org.jetbrains" \
	"-DartifactId=org.jetbrains.intellij-ce" \
	"-Dversion=${IDEA_VERSION}" \
	"-Dpackaging=tar.gz" \
	"-DgeneratePom=true"
	
#rm idea.tar.gz

#----------------------------------------------------------------------#
echo "Downloading IntelliJ IDEA source..."

if [ ! -f idea-src.tar.bz2 ]; then
	wget -O idea-src.tar.bz2 ${IDEA_SRC_URL}
fi

#rm idea-src.tar.bz2

#----------------------------------------------------------------------#
echo "Done!"
