#!/usr/bin/env bash
set -o errexit
set -o pipefail
set -o nounset
#set -o xtrace
__dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
__root="$(cd "$(dirname "${__dir}")" && pwd)"
__file="${__dir}/$(basename "${BASH_SOURCE[0]}")"
__base="$(basename ${__file} .sh)"

arg1="${1:-}"

########################################################################

. generate spoofax
cd eclipse
. ../generate spoofax_eclipse
. ../generate spoofax_eclipse_blue
. ../generate spoofax_eclipse_cyan
. ../generate spoofax_eclipse_green
. ../generate spoofax_eclipse_orange
. ../generate spoofax_eclipse_red

echo "All done!"
