#!/usr/bin/env bash
set -o errexit
set -o pipefail
set -o nounset
# set -o xtrace
__dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
__root="$(cd "$(dirname "${__dir}")" && pwd)"
__file="${__dir}/$(basename "${BASH_SOURCE[0]}")"
__base="$(basename ${__file} .sh)"
arg1="${1:-}"

########################################################################
# Installs IntelliJ IDEA Community Edition
# and creates a shortcut.

echo "Installing IntelliJ IDEA in local directory..."

APPS_DIR="${__dir}/apps"
IDEA_DIR="${APPS_DIR}/idea"
IDEA_SRC_DIR="${IDEA_DIR}/src"
SHORTCUT_DIR="${__dir}"
IDEA_VERSION="14.1.4"
IDEA_URL="https://download.jetbrains.com/idea/ideaIC-${IDEA_VERSION}.tar.gz"
JAVA_HOME=$(readlink -f /usr/bin/javac | sed "s:/bin/javac::")
JAVA_VERSION=$(java -version 2>&1 | head -n 1)

if [[ ! -e "$JAVA_HOME" ]]
then
	echo "Java JDK not found!"
	exit 1
fi

echo "Found Java JDK at: ${JAVA_HOME}"
echo "Version: ${JAVA_VERSION}"
read -r -p "Is this correct? [y/N] " response
response=${response,,}
if [[ ! $response =~ ^(yes|y)$ ]]
then
	exit 0
fi

JAVA_VERSION=$(echo "${JAVA_VERSION}" | sed 's/&/\&amp;/g; s/</\&lt;/g; s/>/\&gt;/g; s/"/\&quot;/g; s/'"'"'/\&#39;/g')

# Download and install IntelliJ IDEA
echo "Downloading IntelliJ IDEA..."
rm -rf ${IDEA_DIR}
mkdir -p ${APPS_DIR}
#wget -O idea.tar.gz ${IDEA_URL}

echo "Installing IntelliJ IDEA..."
tar -zxf idea.tar.gz
mv idea-IC-141.1532.4 ${IDEA_DIR}

# Install IntelliJ IDEA in the local repo
echo "Installing IntelliJ IDEA in local repo..."
mvn install:install-file \
	"-Dfile=idea.tar.gz" \
	"-DgroupId=org.jetbrains" \
	"-DartifactId=org.jetbrains.intellij-ce" \
	"-Dversion=${IDEA_VERSION}" \
	"-Dpackaging=tar.gz" \
	"-DlocalRepositoryPath=../repository" \
	"-DgeneratePom=true"

#rm idea.tar.gz

# Download the source files
echo "Downloading IntelliJ IDEA source..."
#git clone --depth 1 https://github.com/JetBrains/intellij-community.git "${IDEA_SRC_DIR}"
cp -r "${__dir}/src" "${IDEA_SRC_DIR}"

# Move the configuration files
echo "Configuring..."
mkdir -p "${IDEA_DIR}/config/options"
mkdir -p "${IDEA_DIR}/system"

cat << 'EOF' >> "${IDEA_DIR}/bin/idea.properties"
idea.config.path=${idea.home.path}/config
idea.system.path=${idea.home.path}/system
EOF

# Setup the SDKs
cat << EOF > "${IDEA_DIR}/config/options/jdk.table.xml"
<application>
  <component name="ProjectJdkTable">
    <jdk version="2">
      <name value="IntelliJ IDEA Community Edition" />
      <type value="IDEA JDK" />
      <version value="${JAVA_VERSION}" />
      <homePath value="\$APPLICATION_HOME_DIR\$" />
      <roots>
        <annotationsPath>
          <root type="composite">
            <root type="simple" url="jar://\$APPLICATION_HOME_DIR\$/lib/jdkAnnotations.jar!/" />
          </root>
        </annotationsPath>
        <classPath>
          <root type="composite">
            <root type="simple" url="jar://${JAVA_HOME}/jre/lib/jfxswt.jar!/" />
            <root type="simple" url="jar://${JAVA_HOME}/jre/lib/javaws.jar!/" />
            <root type="simple" url="jar://${JAVA_HOME}/jre/lib/rt.jar!/" />
            <root type="simple" url="jar://${JAVA_HOME}/jre/lib/jsse.jar!/" />
            <root type="simple" url="jar://${JAVA_HOME}/jre/lib/plugin.jar!/" />
            <root type="simple" url="jar://${JAVA_HOME}/jre/lib/resources.jar!/" />
            <root type="simple" url="jar://${JAVA_HOME}/jre/lib/jfr.jar!/" />
            <root type="simple" url="jar://${JAVA_HOME}/jre/lib/charsets.jar!/" />
            <root type="simple" url="jar://${JAVA_HOME}/jre/lib/jce.jar!/" />
            <root type="simple" url="jar://${JAVA_HOME}/jre/lib/deploy.jar!/" />
            <root type="simple" url="jar://${JAVA_HOME}/jre/lib/management-agent.jar!/" />
            <root type="simple" url="jar://${JAVA_HOME}/jre/lib/ext/jfxrt.jar!/" />
            <root type="simple" url="jar://${JAVA_HOME}/jre/lib/ext/dnsns.jar!/" />
            <root type="simple" url="jar://${JAVA_HOME}/jre/lib/ext/zipfs.jar!/" />
            <root type="simple" url="jar://${JAVA_HOME}/jre/lib/ext/sunpkcs11.jar!/" />
            <root type="simple" url="jar://${JAVA_HOME}/jre/lib/ext/sunjce_provider.jar!/" />
            <root type="simple" url="jar://${JAVA_HOME}/jre/lib/ext/localedata.jar!/" />
            <root type="simple" url="jar://${JAVA_HOME}/jre/lib/ext/nashorn.jar!/" />
            <root type="simple" url="jar://${JAVA_HOME}/jre/lib/ext/cldrdata.jar!/" />
            <root type="simple" url="jar://${JAVA_HOME}/jre/lib/ext/sunec.jar!/" />
            <root type="simple" url="jar://\$APPLICATION_HOME_DIR\$/lib/junit-4.11.jar!/" />
            <root type="simple" url="jar://\$APPLICATION_HOME_DIR\$/lib/protobuf-2.5.0.jar!/" />
            <root type="simple" url="jar://\$APPLICATION_HOME_DIR\$/lib/winp-1.21-patched.jar!/" />
            <root type="simple" url="jar://\$APPLICATION_HOME_DIR\$/lib/jdom.jar!/" />
            <root type="simple" url="jar://\$APPLICATION_HOME_DIR\$/lib/resources_en.jar!/" />
            <root type="simple" url="jar://\$APPLICATION_HOME_DIR\$/lib/log4j.jar!/" />
            <root type="simple" url="jar://\$APPLICATION_HOME_DIR\$/lib/jps-server.jar!/" />
            <root type="simple" url="jar://\$APPLICATION_HOME_DIR\$/lib/nanoxml-2.2.3.jar!/" />
            <root type="simple" url="jar://\$APPLICATION_HOME_DIR\$/lib/groovy-all-2.3.9.jar!/" />
            <root type="simple" url="jar://\$APPLICATION_HOME_DIR\$/lib/idea.jar!/" />
            <root type="simple" url="jar://\$APPLICATION_HOME_DIR\$/lib/freemarker.jar!/" />
            <root type="simple" url="jar://\$APPLICATION_HOME_DIR\$/lib/jna-utils.jar!/" />
            <root type="simple" url="jar://\$APPLICATION_HOME_DIR\$/lib/slf4j-api-1.7.10.jar!/" />
            <root type="simple" url="jar://\$APPLICATION_HOME_DIR\$/lib/hamcrest-core-1.3.jar!/" />
            <root type="simple" url="jar://\$APPLICATION_HOME_DIR\$/lib/gson-2.3.jar!/" />
            <root type="simple" url="jar://\$APPLICATION_HOME_DIR\$/lib/ecj-4.4.jar!/" />
            <root type="simple" url="jar://\$APPLICATION_HOME_DIR\$/lib/hamcrest-library-1.3.jar!/" />
            <root type="simple" url="jar://\$APPLICATION_HOME_DIR\$/lib/jsch.agentproxy.pageant.jar!/" />
            <root type="simple" url="jar://\$APPLICATION_HOME_DIR\$/lib/microba.jar!/" />
            <root type="simple" url="jar://\$APPLICATION_HOME_DIR\$/lib/jsch.agentproxy.core.jar!/" />
            <root type="simple" url="jar://\$APPLICATION_HOME_DIR\$/lib/sanselan-0.98-snapshot.jar!/" />
            <root type="simple" url="jar://\$APPLICATION_HOME_DIR\$/lib/jsch.agentproxy.usocket-jna.jar!/" />
            <root type="simple" url="jar://\$APPLICATION_HOME_DIR\$/lib/picocontainer.jar!/" />
            <root type="simple" url="jar://\$APPLICATION_HOME_DIR\$/lib/util.jar!/" />
            <root type="simple" url="jar://\$APPLICATION_HOME_DIR\$/lib/fluent-hc-4.3.6.jar!/" />
            <root type="simple" url="jar://\$APPLICATION_HOME_DIR\$/lib/xbean.jar!/" />
            <root type="simple" url="jar://\$APPLICATION_HOME_DIR\$/lib/miglayout-swing.jar!/" />
            <root type="simple" url="jar://\$APPLICATION_HOME_DIR\$/lib/jsch.agentproxy.usocket-nc.jar!/" />
            <root type="simple" url="jar://\$APPLICATION_HOME_DIR\$/lib/trang-core.jar!/" />
            <root type="simple" url="jar://\$APPLICATION_HOME_DIR\$/lib/commons-codec-1.8.jar!/" />
            <root type="simple" url="jar://\$APPLICATION_HOME_DIR\$/lib/boot.jar!/" />
            <root type="simple" url="jar://\$APPLICATION_HOME_DIR\$/lib/xerces.jar!/" />
            <root type="simple" url="jar://\$APPLICATION_HOME_DIR\$/lib/cli-parser-1.1.jar!/" />
            <root type="simple" url="jar://\$APPLICATION_HOME_DIR\$/lib/markdownj-core-0.4.2-SNAPSHOT.jar!/" />
            <root type="simple" url="jar://\$APPLICATION_HOME_DIR\$/lib/nekohtml-1.9.14.jar!/" />
            <root type="simple" url="jar://\$APPLICATION_HOME_DIR\$/lib/javac2.jar!/" />
            <root type="simple" url="jar://\$APPLICATION_HOME_DIR\$/lib/commons-httpclient-3.1-patched.jar!/" />
            <root type="simple" url="jar://\$APPLICATION_HOME_DIR\$/lib/oromatcher.jar!/" />
            <root type="simple" url="jar://\$APPLICATION_HOME_DIR\$/lib/jsr166e.jar!/" />
            <root type="simple" url="jar://\$APPLICATION_HOME_DIR\$/lib/swingx-core-1.6.2.jar!/" />
            <root type="simple" url="jar://\$APPLICATION_HOME_DIR\$/lib/asm-all.jar!/" />
            <root type="simple" url="jar://\$APPLICATION_HOME_DIR\$/lib/icons.jar!/" />
            <root type="simple" url="jar://\$APPLICATION_HOME_DIR\$/lib/asm-commons.jar!/" />
            <root type="simple" url="jar://\$APPLICATION_HOME_DIR\$/lib/jsch-0.1.51.jar!/" />
            <root type="simple" url="jar://\$APPLICATION_HOME_DIR\$/lib/xstream-1.4.3.jar!/" />
            <root type="simple" url="jar://\$APPLICATION_HOME_DIR\$/lib/jgoodies-common-1.2.1.jar!/" />
            <root type="simple" url="jar://\$APPLICATION_HOME_DIR\$/lib/resources.jar!/" />
            <root type="simple" url="jar://\$APPLICATION_HOME_DIR\$/lib/jps-launcher.jar!/" />
            <root type="simple" url="jar://\$APPLICATION_HOME_DIR\$/lib/xmlrpc-2.0.jar!/" />
            <root type="simple" url="jar://\$APPLICATION_HOME_DIR\$/lib/rhino-js-1_7R4.jar!/" />
            <root type="simple" url="jar://\$APPLICATION_HOME_DIR\$/lib/jcip-annotations.jar!/" />
            <root type="simple" url="jar://\$APPLICATION_HOME_DIR\$/lib/proxy-vole_20131209.jar!/" />
            <root type="simple" url="jar://\$APPLICATION_HOME_DIR\$/lib/jaxen-1.1.3.jar!/" />
            <root type="simple" url="jar://\$APPLICATION_HOME_DIR\$/lib/httpclient-4.3.6.jar!/" />
            <root type="simple" url="jar://\$APPLICATION_HOME_DIR\$/lib/jing.jar!/" />
            <root type="simple" url="jar://\$APPLICATION_HOME_DIR\$/lib/forms_rt.jar!/" />
            <root type="simple" url="jar://\$APPLICATION_HOME_DIR\$/lib/trove4j.jar!/" />
            <root type="simple" url="jar://\$APPLICATION_HOME_DIR\$/lib/jgoodies-looks-2.4.2.jar!/" />
            <root type="simple" url="jar://\$APPLICATION_HOME_DIR\$/lib/automaton.jar!/" />
            <root type="simple" url="jar://\$APPLICATION_HOME_DIR\$/lib/jna.jar!/" />
            <root type="simple" url="jar://\$APPLICATION_HOME_DIR\$/lib/cglib-2.2.2.jar!/" />
            <root type="simple" url="jar://\$APPLICATION_HOME_DIR\$/lib/idea_rt.jar!/" />
            <root type="simple" url="jar://\$APPLICATION_HOME_DIR\$/lib/jsr173_1.0_api.jar!/" />
            <root type="simple" url="jar://\$APPLICATION_HOME_DIR\$/lib/jps-model.jar!/" />
            <root type="simple" url="jar://\$APPLICATION_HOME_DIR\$/lib/openapi.jar!/" />
            <root type="simple" url="jar://\$APPLICATION_HOME_DIR\$/lib/serviceMessages.jar!/" />
            <root type="simple" url="jar://\$APPLICATION_HOME_DIR\$/lib/commons-net-3.3.jar!/" />
            <root type="simple" url="jar://\$APPLICATION_HOME_DIR\$/lib/isorelax.jar!/" />
            <root type="simple" url="jar://\$APPLICATION_HOME_DIR\$/lib/markdown4j-2.2.jar!/" />
            <root type="simple" url="jar://\$APPLICATION_HOME_DIR\$/lib/optimizedFileManager.jar!/" />
            <root type="simple" url="jar://\$APPLICATION_HOME_DIR\$/lib/httpmime-4.3.6.jar!/" />
            <root type="simple" url="jar://\$APPLICATION_HOME_DIR\$/lib/annotations.jar!/" />
            <root type="simple" url="jar://\$APPLICATION_HOME_DIR\$/lib/slf4j-log4j12-1.7.10.jar!/" />
            <root type="simple" url="jar://\$APPLICATION_HOME_DIR\$/lib/httpcore-4.3.3.jar!/" />
            <root type="simple" url="jar://\$APPLICATION_HOME_DIR\$/lib/asm.jar!/" />
            <root type="simple" url="jar://\$APPLICATION_HOME_DIR\$/lib/commons-logging-1.1.3.jar!/" />
            <root type="simple" url="jar://\$APPLICATION_HOME_DIR\$/lib/resolver.jar!/" />
            <root type="simple" url="jar://\$APPLICATION_HOME_DIR\$/lib/extensions.jar!/" />
            <root type="simple" url="jar://\$APPLICATION_HOME_DIR\$/lib/purejavacomm.jar!/" />
            <root type="simple" url="jar://\$APPLICATION_HOME_DIR\$/lib/xpp3-1.1.4-min.jar!/" />
            <root type="simple" url="jar://\$APPLICATION_HOME_DIR\$/lib/jayatana-1.2.4.jar!/" />
            <root type="simple" url="jar://\$APPLICATION_HOME_DIR\$/lib/jzlib-1.1.1.jar!/" />
            <root type="simple" url="jar://\$APPLICATION_HOME_DIR\$/lib/jgoodies-forms.jar!/" />
            <root type="simple" url="jar://\$APPLICATION_HOME_DIR\$/lib/rngom-20051226-patched.jar!/" />
            <root type="simple" url="jar://\$APPLICATION_HOME_DIR\$/lib/velocity.jar!/" />
            <root type="simple" url="jar://\$APPLICATION_HOME_DIR\$/lib/asm4-all.jar!/" />
            <root type="simple" url="jar://\$APPLICATION_HOME_DIR\$/lib/jsch.agentproxy.connector-factory.jar!/" />
            <root type="simple" url="jar://\$APPLICATION_HOME_DIR\$/lib/bootstrap.jar!/" />
            <root type="simple" url="jar://\$APPLICATION_HOME_DIR\$/lib/pty4j-0.4.15.jar!/" />
            <root type="simple" url="jar://\$APPLICATION_HOME_DIR\$/lib/jsch.agentproxy.sshagent.jar!/" />
            <root type="simple" url="jar://\$APPLICATION_HOME_DIR\$/lib/trove4j_src.jar!/" />
            <root type="simple" url="jar://\$APPLICATION_HOME_DIR\$/lib/netty-all-4.1.0.Beta4.jar!/" />
            <root type="simple" url="jar://\$APPLICATION_HOME_DIR\$/lib/jh.jar!/" />
            <root type="simple" url="jar://\$APPLICATION_HOME_DIR\$/lib/jdkAnnotations.jar!/" />
            <root type="simple" url="jar://\$APPLICATION_HOME_DIR\$/lib/snappy-in-java-0.3.1.jar!/" />
            <root type="simple" url="jar://\$APPLICATION_HOME_DIR\$/lib/guava-17.0.jar!/" />
          </root>
        </classPath>
        <javadocPath>
          <root type="composite" />
        </javadocPath>
        <sourcePath>
          <root type="composite">
            <root type="simple" url="jar://${JAVA_HOME}/src.zip!/" />
            <root type="simple" url="jar://${JAVA_HOME}/javafx-src.zip!/" />
            <root type="simple" url="file://\$APPLICATION_HOME_DIR\$/src/RegExpSupport/gen" />
            <root type="simple" url="file://\$APPLICATION_HOME_DIR\$/src/RegExpSupport/src" />
            <root type="simple" url="file://\$APPLICATION_HOME_DIR\$/src/RegExpSupport/test" />
            <root type="simple" url="file://\$APPLICATION_HOME_DIR\$/src/build/cucumber-test-runner/src" />
            <root type="simple" url="file://\$APPLICATION_HOME_DIR\$/src/build/src" />
            <root type="simple" url="file://\$APPLICATION_HOME_DIR\$/src/images/src" />
            <root type="simple" url="file://\$APPLICATION_HOME_DIR\$/src/java/compiler/forms-compiler/src" />
            <root type="simple" url="file://\$APPLICATION_HOME_DIR\$/src/java/compiler/forms-compiler/testSrc" />
            <root type="simple" url="file://\$APPLICATION_HOME_DIR\$/src/java/compiler/impl/src" />
            <root type="simple" url="file://\$APPLICATION_HOME_DIR\$/src/java/compiler/impl/testSrc" />
            <root type="simple" url="file://\$APPLICATION_HOME_DIR\$/src/java/compiler/instrumentation-util/src" />
            <root type="simple" url="file://\$APPLICATION_HOME_DIR\$/src/java/compiler/javac2/src" />
            <root type="simple" url="file://\$APPLICATION_HOME_DIR\$/src/java/compiler/openapi/src" />
            <root type="simple" url="file://\$APPLICATION_HOME_DIR\$/src/java/debugger/impl/src" />
            <root type="simple" url="file://\$APPLICATION_HOME_DIR\$/src/java/debugger/openapi/src" />
            <root type="simple" url="file://\$APPLICATION_HOME_DIR\$/src/java/execution/impl/src" />
            <root type="simple" url="file://\$APPLICATION_HOME_DIR\$/src/java/execution/openapi/src" />
            <root type="simple" url="file://\$APPLICATION_HOME_DIR\$/src/java/idea-ui/src" />
            <root type="simple" url="file://\$APPLICATION_HOME_DIR\$/src/java/java-analysis-api/src" />
            <root type="simple" url="file://\$APPLICATION_HOME_DIR\$/src/java/java-analysis-impl/src" />
            <root type="simple" url="file://\$APPLICATION_HOME_DIR\$/src/java/java-impl/gen" />
            <root type="simple" url="file://\$APPLICATION_HOME_DIR\$/src/java/java-impl/src" />
            <root type="simple" url="file://\$APPLICATION_HOME_DIR\$/src/java/java-indexing-api/src" />
            <root type="simple" url="file://\$APPLICATION_HOME_DIR\$/src/java/java-indexing-impl/src" />
            <root type="simple" url="file://\$APPLICATION_HOME_DIR\$/src/java/java-psi-api/src" />
            <root type="simple" url="file://\$APPLICATION_HOME_DIR\$/src/java/java-psi-impl/gen" />
            <root type="simple" url="file://\$APPLICATION_HOME_DIR\$/src/java/java-psi-impl/src" />
            <root type="simple" url="file://\$APPLICATION_HOME_DIR\$/src/java/java-runtime/src" />
            <root type="simple" url="file://\$APPLICATION_HOME_DIR\$/src/java/java-structure-view/src" />
            <root type="simple" url="file://\$APPLICATION_HOME_DIR\$/src/java/java-tests/testSrc" />
            <root type="simple" url="file://\$APPLICATION_HOME_DIR\$/src/java/jsp-base-openapi/src" />
            <root type="simple" url="file://\$APPLICATION_HOME_DIR\$/src/java/jsp-openapi/src" />
            <root type="simple" url="file://\$APPLICATION_HOME_DIR\$/src/java/jsp-spi/src" />
            <root type="simple" url="file://\$APPLICATION_HOME_DIR\$/src/java/manifest/src" />
            <root type="simple" url="file://\$APPLICATION_HOME_DIR\$/src/java/manifest/test" />
            <root type="simple" url="file://\$APPLICATION_HOME_DIR\$/src/java/openapi/src" />
            <root type="simple" url="file://\$APPLICATION_HOME_DIR\$/src/java/remote-servers/api/src" />
            <root type="simple" url="file://\$APPLICATION_HOME_DIR\$/src/java/remote-servers/impl/src" />
            <root type="simple" url="file://\$APPLICATION_HOME_DIR\$/src/java/structuralsearch-java/src" />
            <root type="simple" url="file://\$APPLICATION_HOME_DIR\$/src/java/testFramework/src" />
            <root type="simple" url="file://\$APPLICATION_HOME_DIR\$/src/java/typeMigration/src" />
            <root type="simple" url="file://\$APPLICATION_HOME_DIR\$/src/java/typeMigration/test" />
            <root type="simple" url="file://\$APPLICATION_HOME_DIR\$/src/jps/antLayout/src" />
            <root type="simple" url="file://\$APPLICATION_HOME_DIR\$/src/jps/jps-builders/src" />
            <root type="simple" url="file://\$APPLICATION_HOME_DIR\$/src/jps/jps-builders/testSrc" />
            <root type="simple" url="file://\$APPLICATION_HOME_DIR\$/src/jps/jps-launcher/src" />
            <root type="simple" url="file://\$APPLICATION_HOME_DIR\$/src/jps/model-api/src" />
            <root type="simple" url="file://\$APPLICATION_HOME_DIR\$/src/jps/model-impl/src" />
            <root type="simple" url="file://\$APPLICATION_HOME_DIR\$/src/jps/model-impl/testSrc" />
            <root type="simple" url="file://\$APPLICATION_HOME_DIR\$/src/jps/model-serialization/src" />
            <root type="simple" url="file://\$APPLICATION_HOME_DIR\$/src/jps/model-serialization/testSrc" />
            <root type="simple" url="file://\$APPLICATION_HOME_DIR\$/src/jps/plugin-system/src" />
            <root type="simple" url="file://\$APPLICATION_HOME_DIR\$/src/jps/standalone-builder/src" />
            <root type="simple" url="file://\$APPLICATION_HOME_DIR\$/src/json/gen" />
            <root type="simple" url="file://\$APPLICATION_HOME_DIR\$/src/json/src" />
            <root type="simple" url="file://\$APPLICATION_HOME_DIR\$/src/json/tests/test" />
            <root type="simple" url="file://\$APPLICATION_HOME_DIR\$/src/platform/analysis-api/src" />
            <root type="simple" url="file://\$APPLICATION_HOME_DIR\$/src/platform/analysis-impl/src" />
            <root type="simple" url="file://\$APPLICATION_HOME_DIR\$/src/platform/annotations/common/src" />
            <root type="simple" url="file://\$APPLICATION_HOME_DIR\$/src/platform/annotations/java5/src" />
            <root type="simple" url="file://\$APPLICATION_HOME_DIR\$/src/platform/annotations/java8/src" />
            <root type="simple" url="file://\$APPLICATION_HOME_DIR\$/src/platform/boot/src" />
            <root type="simple" url="file://\$APPLICATION_HOME_DIR\$/src/platform/bootstrap/src" />
            <root type="simple" url="file://\$APPLICATION_HOME_DIR\$/src/platform/built-in-server-api/src" />
            <root type="simple" url="file://\$APPLICATION_HOME_DIR\$/src/platform/built-in-server/src" />
            <root type="simple" url="file://\$APPLICATION_HOME_DIR\$/src/platform/core-api/src" />
            <root type="simple" url="file://\$APPLICATION_HOME_DIR\$/src/platform/core-impl/src" />
            <root type="simple" url="file://\$APPLICATION_HOME_DIR\$/src/platform/diff-api/src" />
            <root type="simple" url="file://\$APPLICATION_HOME_DIR\$/src/platform/diff-impl/src" />
            <root type="simple" url="file://\$APPLICATION_HOME_DIR\$/src/platform/diff-impl/tests" />
            <root type="simple" url="file://\$APPLICATION_HOME_DIR\$/src/platform/duplicates-analysis/src" />
            <root type="simple" url="file://\$APPLICATION_HOME_DIR\$/src/platform/dvcs-api/src" />
            <root type="simple" url="file://\$APPLICATION_HOME_DIR\$/src/platform/dvcs-impl/src" />
            <root type="simple" url="file://\$APPLICATION_HOME_DIR\$/src/platform/editor-ui-api/src" />
            <root type="simple" url="file://\$APPLICATION_HOME_DIR\$/src/platform/editor-ui-ex/src" />
            <root type="simple" url="file://\$APPLICATION_HOME_DIR\$/src/platform/extensions/src" />
            <root type="simple" url="file://\$APPLICATION_HOME_DIR\$/src/platform/extensions/testSrc" />
            <root type="simple" url="file://\$APPLICATION_HOME_DIR\$/src/platform/external-system-api/src" />
            <root type="simple" url="file://\$APPLICATION_HOME_DIR\$/src/platform/external-system-impl/src" />
            <root type="simple" url="file://\$APPLICATION_HOME_DIR\$/src/platform/external-system-impl/testSrc" />
            <root type="simple" url="file://\$APPLICATION_HOME_DIR\$/src/platform/forms_rt/src" />
            <root type="simple" url="file://\$APPLICATION_HOME_DIR\$/src/platform/funcTests/project1/module1/src" />
            <root type="simple" url="file://\$APPLICATION_HOME_DIR\$/src/platform/indexing-api/src" />
            <root type="simple" url="file://\$APPLICATION_HOME_DIR\$/src/platform/indexing-impl/src" />
            <root type="simple" url="file://\$APPLICATION_HOME_DIR\$/src/platform/lang-api/src" />
            <root type="simple" url="file://\$APPLICATION_HOME_DIR\$/src/platform/lang-api/testSources" />
            <root type="simple" url="file://\$APPLICATION_HOME_DIR\$/src/platform/lang-impl/gen" />
            <root type="simple" url="file://\$APPLICATION_HOME_DIR\$/src/platform/lang-impl/src" />
            <root type="simple" url="file://\$APPLICATION_HOME_DIR\$/src/platform/lang-impl/testSources" />
            <root type="simple" url="file://\$APPLICATION_HOME_DIR\$/src/platform/lvcs-api/src" />
            <root type="simple" url="file://\$APPLICATION_HOME_DIR\$/src/platform/lvcs-impl/src" />
            <root type="simple" url="file://\$APPLICATION_HOME_DIR\$/src/platform/platform-api/src" />
            <root type="simple" url="file://\$APPLICATION_HOME_DIR\$/src/platform/platform-impl/src" />
            <root type="simple" url="file://\$APPLICATION_HOME_DIR\$/src/platform/platform-main/src" />
            <root type="simple" url="file://\$APPLICATION_HOME_DIR\$/src/platform/platform-tests/testSrc" />
            <root type="simple" url="file://\$APPLICATION_HOME_DIR\$/src/platform/projectModel-api/src" />
            <root type="simple" url="file://\$APPLICATION_HOME_DIR\$/src/platform/projectModel-impl/src" />
            <root type="simple" url="file://\$APPLICATION_HOME_DIR\$/src/platform/remote-servers/agent-rt/src" />
            <root type="simple" url="file://\$APPLICATION_HOME_DIR\$/src/platform/remote-servers/api/src" />
            <root type="simple" url="file://\$APPLICATION_HOME_DIR\$/src/platform/remote-servers/impl/src" />
            <root type="simple" url="file://\$APPLICATION_HOME_DIR\$/src/platform/script-debugger/backend/src" />
            <root type="simple" url="file://\$APPLICATION_HOME_DIR\$/src/platform/script-debugger/debugger-ui/src" />
            <root type="simple" url="file://\$APPLICATION_HOME_DIR\$/src/platform/script-debugger/debugger-ui/testSrc" />
            <root type="simple" url="file://\$APPLICATION_HOME_DIR\$/src/platform/script-debugger/protocol/protocol-model-generator/generated" />
            <root type="simple" url="file://\$APPLICATION_HOME_DIR\$/src/platform/script-debugger/protocol/protocol-reader-runtime/src" />
            <root type="simple" url="file://\$APPLICATION_HOME_DIR\$/src/platform/smRunner/src" />
            <root type="simple" url="file://\$APPLICATION_HOME_DIR\$/src/platform/smRunner/testSrc" />
            <root type="simple" url="file://\$APPLICATION_HOME_DIR\$/src/platform/structuralsearch/source" />
            <root type="simple" url="file://\$APPLICATION_HOME_DIR\$/src/platform/structuralsearch/testSource" />
            <root type="simple" url="file://\$APPLICATION_HOME_DIR\$/src/platform/structure-view-api/src" />
            <root type="simple" url="file://\$APPLICATION_HOME_DIR\$/src/platform/structure-view-impl/src" />
            <root type="simple" url="file://\$APPLICATION_HOME_DIR\$/src/platform/testFramework/bootstrap/src" />
            <root type="simple" url="file://\$APPLICATION_HOME_DIR\$/src/platform/testFramework/src" />
            <root type="simple" url="file://\$APPLICATION_HOME_DIR\$/src/platform/testFramework/testSrc" />
            <root type="simple" url="file://\$APPLICATION_HOME_DIR\$/src/platform/testRunner/src" />
            <root type="simple" url="file://\$APPLICATION_HOME_DIR\$/src/platform/usageView/src" />
            <root type="simple" url="file://\$APPLICATION_HOME_DIR\$/src/platform/util-rt/src" />
            <root type="simple" url="file://\$APPLICATION_HOME_DIR\$/src/platform/util/src" />
            <root type="simple" url="file://\$APPLICATION_HOME_DIR\$/src/platform/util/testSrc" />
            <root type="simple" url="file://\$APPLICATION_HOME_DIR\$/src/platform/vcs-api/src" />
            <root type="simple" url="file://\$APPLICATION_HOME_DIR\$/src/platform/vcs-api/vcs-api-core/src" />
            <root type="simple" url="file://\$APPLICATION_HOME_DIR\$/src/platform/vcs-impl/src" />
            <root type="simple" url="file://\$APPLICATION_HOME_DIR\$/src/platform/vcs-impl/testSrc" />
            <root type="simple" url="file://\$APPLICATION_HOME_DIR\$/src/platform/vcs-log/api/src" />
            <root type="simple" url="file://\$APPLICATION_HOME_DIR\$/src/platform/vcs-log/graph-api/src" />
            <root type="simple" url="file://\$APPLICATION_HOME_DIR\$/src/platform/vcs-log/graph/src" />
            <root type="simple" url="file://\$APPLICATION_HOME_DIR\$/src/platform/vcs-log/graph/test" />
            <root type="simple" url="file://\$APPLICATION_HOME_DIR\$/src/platform/vcs-log/impl/gen" />
            <root type="simple" url="file://\$APPLICATION_HOME_DIR\$/src/platform/vcs-log/impl/src" />
            <root type="simple" url="file://\$APPLICATION_HOME_DIR\$/src/platform/vcs-log/impl/test" />
            <root type="simple" url="file://\$APPLICATION_HOME_DIR\$/src/platform/xdebugger-api/src" />
            <root type="simple" url="file://\$APPLICATION_HOME_DIR\$/src/platform/xdebugger-impl/src" />
            <root type="simple" url="file://\$APPLICATION_HOME_DIR\$/src/platform/xdebugger-impl/testSrc" />
            <root type="simple" url="file://\$APPLICATION_HOME_DIR\$/src/plugins/ByteCodeViewer/src" />
            <root type="simple" url="file://\$APPLICATION_HOME_DIR\$/src/plugins/InspectionGadgets/InspectionGadgetsAnalysis/src" />
            <root type="simple" url="file://\$APPLICATION_HOME_DIR\$/src/plugins/InspectionGadgets/src" />
            <root type="simple" url="file://\$APPLICATION_HOME_DIR\$/src/plugins/InspectionGadgets/test" />
            <root type="simple" url="file://\$APPLICATION_HOME_DIR\$/src/plugins/InspectionGadgets/testsrc" />
            <root type="simple" url="file://\$APPLICATION_HOME_DIR\$/src/plugins/IntelliLang/IntelliLang-tests/test" />
            <root type="simple" url="file://\$APPLICATION_HOME_DIR\$/src/plugins/IntelliLang/intellilang-jps-plugin/src" />
            <root type="simple" url="file://\$APPLICATION_HOME_DIR\$/src/plugins/IntelliLang/java-support" />
            <root type="simple" url="file://\$APPLICATION_HOME_DIR\$/src/plugins/IntelliLang/src" />
            <root type="simple" url="file://\$APPLICATION_HOME_DIR\$/src/plugins/IntelliLang/xml-support" />
            <root type="simple" url="file://\$APPLICATION_HOME_DIR\$/src/plugins/IntentionPowerPak/src" />
            <root type="simple" url="file://\$APPLICATION_HOME_DIR\$/src/plugins/IntentionPowerPak/test" />
            <root type="simple" url="file://\$APPLICATION_HOME_DIR\$/src/plugins/IntentionPowerPak/testSrc" />
            <root type="simple" url="file://\$APPLICATION_HOME_DIR\$/src/plugins/ShortcutPromoter/src" />
            <root type="simple" url="file://\$APPLICATION_HOME_DIR\$/src/plugins/ant/jps-plugin/src" />
            <root type="simple" url="file://\$APPLICATION_HOME_DIR\$/src/plugins/ant/jps-plugin/testSrc" />
            <root type="simple" url="file://\$APPLICATION_HOME_DIR\$/src/plugins/ant/src" />
            <root type="simple" url="file://\$APPLICATION_HOME_DIR\$/src/plugins/ant/tests/src" />
            <root type="simple" url="file://\$APPLICATION_HOME_DIR\$/src/plugins/commander/src" />
            <root type="simple" url="file://\$APPLICATION_HOME_DIR\$/src/plugins/copyright/src" />
            <root type="simple" url="file://\$APPLICATION_HOME_DIR\$/src/plugins/coverage-common/src" />
            <root type="simple" url="file://\$APPLICATION_HOME_DIR\$/src/plugins/coverage/src" />
            <root type="simple" url="file://\$APPLICATION_HOME_DIR\$/src/plugins/coverage/testSrc" />
            <root type="simple" url="file://\$APPLICATION_HOME_DIR\$/src/plugins/cucumber-jvm-formatter/src" />
            <root type="simple" url="file://\$APPLICATION_HOME_DIR\$/src/plugins/cvs/cvs-core/src" />
            <root type="simple" url="file://\$APPLICATION_HOME_DIR\$/src/plugins/cvs/cvs-plugin/src" />
            <root type="simple" url="file://\$APPLICATION_HOME_DIR\$/src/plugins/cvs/javacvs-src" />
            <root type="simple" url="file://\$APPLICATION_HOME_DIR\$/src/plugins/cvs/smartcvs-src" />
            <root type="simple" url="file://\$APPLICATION_HOME_DIR\$/src/plugins/cvs/trilead-ssh2-build213/examples" />
            <root type="simple" url="file://\$APPLICATION_HOME_DIR\$/src/plugins/cvs/trilead-ssh2-build213/src" />
            <root type="simple" url="file://\$APPLICATION_HOME_DIR\$/src/plugins/devkit/gen" />
            <root type="simple" url="file://\$APPLICATION_HOME_DIR\$/src/plugins/devkit/jps-plugin/src" />
            <root type="simple" url="file://\$APPLICATION_HOME_DIR\$/src/plugins/devkit/jps-plugin/testSrc" />
            <root type="simple" url="file://\$APPLICATION_HOME_DIR\$/src/plugins/eclipse/gen" />
            <root type="simple" url="file://\$APPLICATION_HOME_DIR\$/src/plugins/eclipse/jps-plugin/src" />
            <root type="simple" url="file://\$APPLICATION_HOME_DIR\$/src/plugins/eclipse/src" />
            <root type="simple" url="file://\$APPLICATION_HOME_DIR\$/src/plugins/eclipse/testSources" />
            <root type="simple" url="file://\$APPLICATION_HOME_DIR\$/src/plugins/editorconfig/src" />
            <root type="simple" url="file://\$APPLICATION_HOME_DIR\$/src/plugins/generate-tostring/src" />
            <root type="simple" url="file://\$APPLICATION_HOME_DIR\$/src/plugins/generate-tostring/testSrc" />
            <root type="simple" url="file://\$APPLICATION_HOME_DIR\$/src/plugins/git4idea/remote-servers-git/src" />
            <root type="simple" url="file://\$APPLICATION_HOME_DIR\$/src/plugins/git4idea/resources" />
            <root type="simple" url="file://\$APPLICATION_HOME_DIR\$/src/plugins/git4idea/rt/src" />
            <root type="simple" url="file://\$APPLICATION_HOME_DIR\$/src/plugins/git4idea/src" />
            <root type="simple" url="file://\$APPLICATION_HOME_DIR\$/src/plugins/git4idea/test-stepdefs" />
            <root type="simple" url="file://\$APPLICATION_HOME_DIR\$/src/plugins/git4idea/tests" />
            <root type="simple" url="file://\$APPLICATION_HOME_DIR\$/src/plugins/github/src" />
            <root type="simple" url="file://\$APPLICATION_HOME_DIR\$/src/plugins/github/test" />
            <root type="simple" url="file://\$APPLICATION_HOME_DIR\$/src/plugins/google-app-engine/gen" />
            <root type="simple" url="file://\$APPLICATION_HOME_DIR\$/src/plugins/google-app-engine/jps-plugin/src" />
            <root type="simple" url="file://\$APPLICATION_HOME_DIR\$/src/plugins/google-app-engine/jps-plugin/testSource" />
            <root type="simple" url="file://\$APPLICATION_HOME_DIR\$/src/plugins/google-app-engine/runtime/source" />
            <root type="simple" url="file://\$APPLICATION_HOME_DIR\$/src/plugins/google-app-engine/source" />
            <root type="simple" url="file://\$APPLICATION_HOME_DIR\$/src/plugins/google-app-engine/testSource" />
            <root type="simple" url="file://\$APPLICATION_HOME_DIR\$/src/plugins/gradle/jps-plugin/src" />
            <root type="simple" url="file://\$APPLICATION_HOME_DIR\$/src/plugins/gradle/src" />
            <root type="simple" url="file://\$APPLICATION_HOME_DIR\$/src/plugins/gradle/testSources" />
            <root type="simple" url="file://\$APPLICATION_HOME_DIR\$/src/plugins/gradle/tooling-extension-api/src" />
            <root type="simple" url="file://\$APPLICATION_HOME_DIR\$/src/plugins/gradle/tooling-extension-impl/src" />
            <root type="simple" url="file://\$APPLICATION_HOME_DIR\$/src/plugins/gradle/tooling-extension-impl/testSources" />
            <root type="simple" url="file://\$APPLICATION_HOME_DIR\$/src/plugins/groovy/groovy-psi/gen" />
            <root type="simple" url="file://\$APPLICATION_HOME_DIR\$/src/plugins/groovy/groovy-psi/src" />
            <root type="simple" url="file://\$APPLICATION_HOME_DIR\$/src/plugins/groovy/hotswap/agentSrc" />
            <root type="simple" url="file://\$APPLICATION_HOME_DIR\$/src/plugins/groovy/jps-plugin/src" />
            <root type="simple" url="file://\$APPLICATION_HOME_DIR\$/src/plugins/groovy/rt-constants/src" />
            <root type="simple" url="file://\$APPLICATION_HOME_DIR\$/src/plugins/groovy/rt/src" />
            <root type="simple" url="file://\$APPLICATION_HOME_DIR\$/src/plugins/groovy/src" />
            <root type="simple" url="file://\$APPLICATION_HOME_DIR\$/src/plugins/groovy/structuralsearch-groovy/src" />
            <root type="simple" url="file://\$APPLICATION_HOME_DIR\$/src/plugins/groovy/structuralsearch-groovy/testSrc" />
            <root type="simple" url="file://\$APPLICATION_HOME_DIR\$/src/plugins/groovy/test" />
            <root type="simple" url="file://\$APPLICATION_HOME_DIR\$/src/plugins/hg4idea/src" />
            <root type="simple" url="file://\$APPLICATION_HOME_DIR\$/src/plugins/hg4idea/testSrc" />
            <root type="simple" url="file://\$APPLICATION_HOME_DIR\$/src/plugins/java-decompiler/engine/src" />
            <root type="simple" url="file://\$APPLICATION_HOME_DIR\$/src/plugins/java-decompiler/engine/test" />
            <root type="simple" url="file://\$APPLICATION_HOME_DIR\$/src/plugins/java-decompiler/plugin/src" />
            <root type="simple" url="file://\$APPLICATION_HOME_DIR\$/src/plugins/java-decompiler/plugin/test" />
            <root type="simple" url="file://\$APPLICATION_HOME_DIR\$/src/plugins/java-i18n/src" />
            <root type="simple" url="file://\$APPLICATION_HOME_DIR\$/src/plugins/java-i18n/testSrc" />
            <root type="simple" url="file://\$APPLICATION_HOME_DIR\$/src/plugins/javaFX/FxBuilderEmbedder/src" />
            <root type="simple" url="file://\$APPLICATION_HOME_DIR\$/src/plugins/javaFX/common-javaFX-plugin/src" />
            <root type="simple" url="file://\$APPLICATION_HOME_DIR\$/src/plugins/javaFX/javaFX-CE/testSrc" />
            <root type="simple" url="file://\$APPLICATION_HOME_DIR\$/src/plugins/javaFX/javaFX-jps-plugin/src" />
            <root type="simple" url="file://\$APPLICATION_HOME_DIR\$/src/plugins/javaFX/src" />
            <root type="simple" url="file://\$APPLICATION_HOME_DIR\$/src/plugins/junit/src" />
            <root type="simple" url="file://\$APPLICATION_HOME_DIR\$/src/plugins/junit/test" />
            <root type="simple" url="file://\$APPLICATION_HOME_DIR\$/src/plugins/junit_rt/src" />
            <root type="simple" url="file://\$APPLICATION_HOME_DIR\$/src/plugins/maven/artifact-resolver-m2/src" />
            <root type="simple" url="file://\$APPLICATION_HOME_DIR\$/src/plugins/maven/artifact-resolver-m3/src" />
            <root type="simple" url="file://\$APPLICATION_HOME_DIR\$/src/plugins/maven/artifact-resolver-m31/src" />
            <root type="simple" url="file://\$APPLICATION_HOME_DIR\$/src/plugins/maven/jps-plugin/src" />
            <root type="simple" url="file://\$APPLICATION_HOME_DIR\$/src/plugins/maven/jps-plugin/testSrc" />
            <root type="simple" url="file://\$APPLICATION_HOME_DIR\$/src/plugins/maven/maven-server-api/src" />
            <root type="simple" url="file://\$APPLICATION_HOME_DIR\$/src/plugins/maven/maven2-server-impl/src" />
            <root type="simple" url="file://\$APPLICATION_HOME_DIR\$/src/plugins/maven/maven2-server-impl/test" />
            <root type="simple" url="file://\$APPLICATION_HOME_DIR\$/src/plugins/maven/maven3-server-common/src" />
            <root type="simple" url="file://\$APPLICATION_HOME_DIR\$/src/plugins/maven/maven30-server-impl/src" />
            <root type="simple" url="file://\$APPLICATION_HOME_DIR\$/src/plugins/maven/maven32-server-impl/src" />
            <root type="simple" url="file://\$APPLICATION_HOME_DIR\$/src/plugins/maven/src/main/java" />
            <root type="simple" url="file://\$APPLICATION_HOME_DIR\$/src/plugins/maven/src/test/java" />
            <root type="simple" url="file://\$APPLICATION_HOME_DIR\$/src/plugins/properties/properties-psi-api/gen" />
            <root type="simple" url="file://\$APPLICATION_HOME_DIR\$/src/plugins/properties/properties-psi-api/src" />
            <root type="simple" url="file://\$APPLICATION_HOME_DIR\$/src/plugins/properties/properties-psi-impl/src" />
            <root type="simple" url="file://\$APPLICATION_HOME_DIR\$/src/plugins/properties/src" />
            <root type="simple" url="file://\$APPLICATION_HOME_DIR\$/src/plugins/properties/testSrc" />
            <root type="simple" url="file://\$APPLICATION_HOME_DIR\$/src/plugins/svn4idea/resources" />
            <root type="simple" url="file://\$APPLICATION_HOME_DIR\$/src/plugins/svn4idea/src" />
            <root type="simple" url="file://\$APPLICATION_HOME_DIR\$/src/plugins/svn4idea/testSource" />
            <root type="simple" url="file://\$APPLICATION_HOME_DIR\$/src/plugins/tasks/tasks-api/src" />
            <root type="simple" url="file://\$APPLICATION_HOME_DIR\$/src/plugins/tasks/tasks-core/jira/gen" />
            <root type="simple" url="file://\$APPLICATION_HOME_DIR\$/src/plugins/tasks/tasks-core/jira/src" />
            <root type="simple" url="file://\$APPLICATION_HOME_DIR\$/src/plugins/tasks/tasks-core/src" />
            <root type="simple" url="file://\$APPLICATION_HOME_DIR\$/src/plugins/tasks/tasks-java/src" />
            <root type="simple" url="file://\$APPLICATION_HOME_DIR\$/src/plugins/tasks/tasks-tests/test" />
            <root type="simple" url="file://\$APPLICATION_HOME_DIR\$/src/plugins/terminal/src" />
            <root type="simple" url="file://\$APPLICATION_HOME_DIR\$/src/plugins/testng/src" />
            <root type="simple" url="file://\$APPLICATION_HOME_DIR\$/src/plugins/testng/testSources" />
            <root type="simple" url="file://\$APPLICATION_HOME_DIR\$/src/plugins/testng_rt/src" />
            <root type="simple" url="file://\$APPLICATION_HOME_DIR\$/src/plugins/ui-designer-core/src" />
            <root type="simple" url="file://\$APPLICATION_HOME_DIR\$/src/plugins/ui-designer/jps-plugin/src" />
            <root type="simple" url="file://\$APPLICATION_HOME_DIR\$/src/plugins/ui-designer/jps-plugin/testSrc" />
            <root type="simple" url="file://\$APPLICATION_HOME_DIR\$/src/plugins/ui-designer/src" />
            <root type="simple" url="file://\$APPLICATION_HOME_DIR\$/src/plugins/ui-designer/testSrc" />
            <root type="simple" url="file://\$APPLICATION_HOME_DIR\$/src/plugins/xpath/xpath-lang/src" />
            <root type="simple" url="file://\$APPLICATION_HOME_DIR\$/src/plugins/xpath/xpath-lang/test" />
            <root type="simple" url="file://\$APPLICATION_HOME_DIR\$/src/plugins/xpath/xpath-view/src" />
            <root type="simple" url="file://\$APPLICATION_HOME_DIR\$/src/plugins/xpath/xslt-rt/src" />
            <root type="simple" url="file://\$APPLICATION_HOME_DIR\$/src/plugins/xslt-debugger/engine/impl/src" />
            <root type="simple" url="file://\$APPLICATION_HOME_DIR\$/src/plugins/xslt-debugger/engine/src" />
            <root type="simple" url="file://\$APPLICATION_HOME_DIR\$/src/plugins/xslt-debugger/rt/impl/src" />
            <root type="simple" url="file://\$APPLICATION_HOME_DIR\$/src/plugins/xslt-debugger/src" />
            <root type="simple" url="file://\$APPLICATION_HOME_DIR\$/src/python/IntelliLang-python/src" />
            <root type="simple" url="file://\$APPLICATION_HOME_DIR\$/src/python/edu/course-creator-intellij-py/src" />
            <root type="simple" url="file://\$APPLICATION_HOME_DIR\$/src/python/edu/course-creator-python/src" />
            <root type="simple" url="file://\$APPLICATION_HOME_DIR\$/src/python/edu/course-creator-python/tests" />
            <root type="simple" url="file://\$APPLICATION_HOME_DIR\$/src/python/edu/interactive-learning-intellij-py/src" />
            <root type="simple" url="file://\$APPLICATION_HOME_DIR\$/src/python/edu/interactive-learning-python/src" />
            <root type="simple" url="file://\$APPLICATION_HOME_DIR\$/src/python/edu/src" />
            <root type="simple" url="file://\$APPLICATION_HOME_DIR\$/src/python/educational/course-creator/src" />
            <root type="simple" url="file://\$APPLICATION_HOME_DIR\$/src/python/educational/interactive-learning-intellij/src" />
            <root type="simple" url="file://\$APPLICATION_HOME_DIR\$/src/python/educational/interactive-learning/src" />
            <root type="simple" url="file://\$APPLICATION_HOME_DIR\$/src/python/educational/src" />
            <root type="simple" url="file://\$APPLICATION_HOME_DIR\$/src/python/gen" />
            <root type="simple" url="file://\$APPLICATION_HOME_DIR\$/src/python/ide/src" />
            <root type="simple" url="file://\$APPLICATION_HOME_DIR\$/src/python/ipnb/src" />
            <root type="simple" url="file://\$APPLICATION_HOME_DIR\$/src/python/ipnb/testSrc" />
            <root type="simple" url="file://\$APPLICATION_HOME_DIR\$/src/python/openapi/src" />
            <root type="simple" url="file://\$APPLICATION_HOME_DIR\$/src/python/pluginSrc" />
            <root type="simple" url="file://\$APPLICATION_HOME_DIR\$/src/python/pluginTestSrc" />
            <root type="simple" url="file://\$APPLICATION_HOME_DIR\$/src/python/psi-api/src" />
            <root type="simple" url="file://\$APPLICATION_HOME_DIR\$/src/python/pydevSrc" />
            <root type="simple" url="file://\$APPLICATION_HOME_DIR\$/src/python/python-rest/src" />
            <root type="simple" url="file://\$APPLICATION_HOME_DIR\$/src/python/python-rest/test" />
            <root type="simple" url="file://\$APPLICATION_HOME_DIR\$/src/python/rest/gen" />
            <root type="simple" url="file://\$APPLICATION_HOME_DIR\$/src/python/rest/src" />
            <root type="simple" url="file://\$APPLICATION_HOME_DIR\$/src/python/src" />
            <root type="simple" url="file://\$APPLICATION_HOME_DIR\$/src/python/testSrc" />
            <root type="simple" url="file://\$APPLICATION_HOME_DIR\$/src/samples/comparingReferences/source" />
            <root type="simple" url="file://\$APPLICATION_HOME_DIR\$/src/samples/comparingReferences/testSource" />
            <root type="simple" url="file://\$APPLICATION_HOME_DIR\$/src/samples/conditionalOperatorConvertor/source" />
            <root type="simple" url="file://\$APPLICATION_HOME_DIR\$/src/samples/conditionalOperatorConvertor/testSource" />
            <root type="simple" url="file://\$APPLICATION_HOME_DIR\$/src/spellchecker/src" />
            <root type="simple" url="file://\$APPLICATION_HOME_DIR\$/src/spellchecker/testSrc" />
            <root type="simple" url="file://\$APPLICATION_HOME_DIR\$/src/tools/launcher-generator/src" />
            <root type="simple" url="file://\$APPLICATION_HOME_DIR\$/src/tools/lexer/jflex-1.4/examples/binary" />
            <root type="simple" url="file://\$APPLICATION_HOME_DIR\$/src/tools/lexer/jflex-1.4/examples/cup" />
            <root type="simple" url="file://\$APPLICATION_HOME_DIR\$/src/tools/lexer/jflex-1.4/examples/interpreter" />
            <root type="simple" url="file://\$APPLICATION_HOME_DIR\$/src/tools/lexer/jflex-1.4/examples/java" />
            <root type="simple" url="file://\$APPLICATION_HOME_DIR\$/src/tools/lexer/jflex-1.4/examples/simple" />
            <root type="simple" url="file://\$APPLICATION_HOME_DIR\$/src/tools/lexer/jflex-1.4/src" />
            <root type="simple" url="file://\$APPLICATION_HOME_DIR\$/src/updater/src" />
            <root type="simple" url="file://\$APPLICATION_HOME_DIR\$/src/updater/testSrc" />
            <root type="simple" url="file://\$APPLICATION_HOME_DIR\$/src/xml/dom-impl/src" />
            <root type="simple" url="file://\$APPLICATION_HOME_DIR\$/src/xml/dom-openapi/src" />
            <root type="simple" url="file://\$APPLICATION_HOME_DIR\$/src/xml/dom-tests/tests" />
            <root type="simple" url="file://\$APPLICATION_HOME_DIR\$/src/xml/impl/src" />
            <root type="simple" url="file://\$APPLICATION_HOME_DIR\$/src/xml/openapi/src" />
            <root type="simple" url="file://\$APPLICATION_HOME_DIR\$/src/xml/relaxng/src" />
            <root type="simple" url="file://\$APPLICATION_HOME_DIR\$/src/xml/relaxng/test" />
            <root type="simple" url="file://\$APPLICATION_HOME_DIR\$/src/xml/tests/src" />
            <root type="simple" url="file://\$APPLICATION_HOME_DIR\$/src/xml/xml-analysis-api/src" />
            <root type="simple" url="file://\$APPLICATION_HOME_DIR\$/src/xml/xml-analysis-impl/src" />
            <root type="simple" url="file://\$APPLICATION_HOME_DIR\$/src/xml/xml-psi-api/src" />
            <root type="simple" url="file://\$APPLICATION_HOME_DIR\$/src/xml/xml-psi-impl/gen" />
            <root type="simple" url="file://\$APPLICATION_HOME_DIR\$/src/xml/xml-psi-impl/src" />
            <root type="simple" url="file://\$APPLICATION_HOME_DIR\$/src/xml/xml-structure-view-api/src" />
            <root type="simple" url="file://\$APPLICATION_HOME_DIR\$/src/xml/xml-structure-view-impl/src" />
          </root>
        </sourcePath>
      </roots>
      <additional sdk="1.8">
        <option name="mySandboxHome" value="\$USER_HOME\$/.IdeaIC14/system/plugins-sandbox" />
      </additional>
    </jdk>
    <jdk version="2">
      <name value="1.8" />
      <type value="JavaSDK" />
      <version value="java version &quot;1.8.0_45&quot;" />
      <homePath value="${JAVA_HOME}" />
      <roots>
        <annotationsPath>
          <root type="composite">
            <root type="simple" url="jar://\$APPLICATION_HOME_DIR\$/lib/jdkAnnotations.jar!/" />
          </root>
        </annotationsPath>
        <classPath>
          <root type="composite">
            <root type="simple" url="jar://${JAVA_HOME}/jre/lib/jfxswt.jar!/" />
            <root type="simple" url="jar://${JAVA_HOME}/jre/lib/javaws.jar!/" />
            <root type="simple" url="jar://${JAVA_HOME}/jre/lib/rt.jar!/" />
            <root type="simple" url="jar://${JAVA_HOME}/jre/lib/jsse.jar!/" />
            <root type="simple" url="jar://${JAVA_HOME}/jre/lib/plugin.jar!/" />
            <root type="simple" url="jar://${JAVA_HOME}/jre/lib/resources.jar!/" />
            <root type="simple" url="jar://${JAVA_HOME}/jre/lib/jfr.jar!/" />
            <root type="simple" url="jar://${JAVA_HOME}/jre/lib/charsets.jar!/" />
            <root type="simple" url="jar://${JAVA_HOME}/jre/lib/jce.jar!/" />
            <root type="simple" url="jar://${JAVA_HOME}/jre/lib/deploy.jar!/" />
            <root type="simple" url="jar://${JAVA_HOME}/jre/lib/management-agent.jar!/" />
            <root type="simple" url="jar://${JAVA_HOME}/jre/lib/ext/jfxrt.jar!/" />
            <root type="simple" url="jar://${JAVA_HOME}/jre/lib/ext/dnsns.jar!/" />
            <root type="simple" url="jar://${JAVA_HOME}/jre/lib/ext/zipfs.jar!/" />
            <root type="simple" url="jar://${JAVA_HOME}/jre/lib/ext/sunpkcs11.jar!/" />
            <root type="simple" url="jar://${JAVA_HOME}/jre/lib/ext/sunjce_provider.jar!/" />
            <root type="simple" url="jar://${JAVA_HOME}/jre/lib/ext/localedata.jar!/" />
            <root type="simple" url="jar://${JAVA_HOME}/jre/lib/ext/nashorn.jar!/" />
            <root type="simple" url="jar://${JAVA_HOME}/jre/lib/ext/cldrdata.jar!/" />
            <root type="simple" url="jar://${JAVA_HOME}/jre/lib/ext/sunec.jar!/" />
          </root>
        </classPath>
        <javadocPath>
          <root type="composite" />
        </javadocPath>
        <sourcePath>
          <root type="composite">
            <root type="simple" url="jar://${JAVA_HOME}/src.zip!/" />
            <root type="simple" url="jar://${JAVA_HOME}/javafx-src.zip!/" />
          </root>
        </sourcePath>
      </roots>
      <additional />
    </jdk>
  </component>
</application>
EOF

# Create shortcut
echo "Creating desktop shortcut..."
cat << EOF > "${SHORTCUT_DIR}/intellij.desktop"
[Desktop Entry]
Encoding=UTF-8
Name=IntelliJ
Comment=IntelliJ IDEA Community Edition
Exec=${APPS_DIR}/intellij/bin/idea.sh
Icon=${APPS_DIR}/intellij/bin/idea.png
Terminal=false
Type=Application
Categories=GNOME;Application;Development;
StartupNotify=true
EOF

echo "Done!"
echo "IntelliJ IDEA installed to ${IDEA_DIR}"
echo "Run ${IDEA_DIR}/bin/idea.sh"
echo "or copy the shortcut to the desktop."
